clc;
clear all;
close all;
vidReader = VideoReader('22.mp4'); %input your sample video here, keep it in same folder as the file

outputVideo = VideoWriter('roadHighlight.mp4', 'MPEG-4');
outputVideo.FrameRate = vidReader.FrameRate;
open(outputVideo);

videoPlayer = vision.VideoPlayer('Name', 'Road Highlight', ...
    'Position', [100, 100, 700, 400]); % An Output file named Road Highlight will be creaated which highlights the lane in the sample video


while hasFrame(vidReader)
    frame = readFrame(vidReader);
    grayFrame = rgb2gray(frame);
    se = strel('disk', 2);  
    [BW, ~] = segmentImage(grayFrame);
    BW = imclose(BW, se);
    overlay = uint8(cat(3, 255 * BW, 255 * BW, zeros(size(BW), 'uint8')));
    
    alpha = 0.5;
    highlightedFrame = frame;
    highlightedFrame(BW) = uint8((1 - alpha) * double(frame(BW)) + alpha * double(overlay(BW)));
    
    step(videoPlayer, highlightedFrame);
    writeVideo(outputVideo, highlightedFrame);
end

release(videoPlayer);
close(outputVideo);


function [BW,maskedImage] = segmentImage(X)
%segmentImage Segment image using auto-generated code from Image Segmenter app
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the Image Segmenter app. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 07-Jun-2025
%----------------------------------------------------


% Adjust data to span data range.
X = imadjust(X);

% Create empty mask
BW = false(size(X,1),size(X,2));

% Draw ROIs

xPos = [0.5000 517.7603 1019.2397 1646.9658 2155.4589 2772.6644 3277.6507 3838.7466 3831.7329 2979.5685 2520.1712 2053.7603 1366.4178 892.9932 2.2534];
yPos = [1098.0041 908.9603 733.9198 562.3801 544.8760 754.9246 950.9700 1185.5243 1483.0932 1416.5778 1238.0365 1220.5324 1273.0446 1511.0997 1623.1256];
m = size(BW, 1);
n = size(BW, 2);
addedRegion = poly2mask(xPos, yPos, m, n);
BW = BW | addedRegion;

% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;
end



